### ISSUE TITLE
Update DESCRIPTION with CRAN submission comments

### ISSUE THREAD

**Issue by wangw106** [phuse-org/sendigR#17]
Please reduce the length of the title to less than 65 characters.

Please do not start the description with "This package", package name, title, "A set of functions" or similar.

Please always write package names, software names and API (application programming interface) names in single quotes in title and description.
e.g: --> 'SQLite'; 'Oracle'; 'CDISC'
Please note that package names are case sensitive.

**Comment by Yousuf28** [comment]
just curious, Why 'CDISC' and 'SEND' in single quote?
is this package names, or 
software names or
 API (application programming interface)?

A reference without quote:
https://github.com/atorus-research/xportr
